[book]
title = "Portfolio of tobiO0310"
authors = ["tobiO0310"]
language = "en"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
mathjax-support = true
